name: Build Resourcepack

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4

    - name: Create resourcepack zip
      run: |
        zip -r ShadowBlade-resourcepack.zip . -x ".git/*" ".github/*" ".*" "*.md"

    - name: Upload to Release (always to 'latest')
      uses: softprops/action-gh-release@v2
      with:
        files: ShadowBlade-resourcepack.zip
        tag_name: "latest"
        name: "ShadowBlade Resourcepack"
        body: "Наш ресурспак! Бананчики :3"
        draft: false
        prerelease: false
        make_latest: "legacy"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
